### ISSUE TITLE
Can use this plugin to add unit test and run the unit tests in the Unreal Engine?

### ISSUE THREAD

**Issue by ghost** [DaedalicEntertainment/ue4-test-automation#14]
This is a great tool!

I understand to use a blueprint is a medium test, and currently Unreal Engine have lots of unit tests like `TimespanTest.cpp`. The plugin can run such unt tests? And how to add the unt tests via this tool?

**Comment by janousch** [comment]
Hi, at the moment it is not possible to run unit tests with this plugin.
The functional tests cost a lot of time to run and this is why we plan to support unit tests in the future.
