### ISSUE TITLE
4.25.3 -> 4.26.0: DaeTestPerformanceBudgetActor.cpp: cannot convert from 'const float [4]' to 'float'

### ISSUE THREAD

**Issue by helghast** [DaedalicEntertainment/ue4-test-automation#17]
Migrating to version 4.26:

`1>E:/UnrealEngineProjects2/AutomatedTestingTDD/Plugins/DaedalicTestAutomationPlugin/Source/DaedalicTestAutomationPlugin/Private/DaeTestPerformanceBudgetActor.cpp(193): error C2440: 'initializing': cannot convert from 'const float [4]' to 'float'
1>  E:/UnrealEngineProjects2/AutomatedTestingTDD/Plugins/DaedalicTestAutomationPlugin/Source/DaedalicTestAutomationPlugin/Private/DaeTestPerformanceBudgetActor.cpp(193): note: There is no context in which this conversion is possible`

![image](https://user-images.githubusercontent.com/7014938/105190381-3aee7600-5b36-11eb-8804-7acdefd4163f.png)

**Comment by WuAlan** [comment]
I temply resolve this by just use gpu[0] time here..

**Comment by MarceloGOliveira** [comment]
In a project created with version 4.26, in addition to the error above, there is another one:

`DaeTestPerformanceBudgetActor.cpp(81): error C2248: 'AActor::Instigator': cannot access private member declared in class 'AActor'
`

![ErroBuildPlugin](https://user-images.githubusercontent.com/23239215/127919796-faa97c69-9577-4eff-9d46-b8a647b406a9.PNG)

**Comment by NorfolkNChance** [comment]
> In a project created with version 4.26, in addition to the error above, there is another one:
> 
> `DaeTestPerformanceBudgetActor.cpp(81): error C2248: 'AActor::Instigator': cannot access private member declared in class 'AActor' `
> 
> ![ErroBuildPlugin](https://user-images.githubusercontent.com/23239215/127919796-faa97c69-9577-4eff-9d46-b8a647b406a9.PNG)

Change to 
SpawnInfo.Instigator = GetInstigator();

**Comment by janousch** [comment]
Fixed in commit 6539ae02362971ba307a8505ca49819adbe3f875  .
