### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by DaedalicEntertainment** [DaedalicEntertainment/ue4-test-automation#2]
Add utility actors and functions for testing the performance of a game, e.g. by rotating the camera around a specific location and measuring performance, then taking a screenshot of the location for reference.

See whether we can borrow anything from UAutomationPerformaceHelper and AScreenshotFunctionalTestBase.

**Comment by npruehs** [comment]
Added in commit f306a5a5641762bb4a1cf33603b705ef52d0cf86.
