### ISSUE TITLE
Support for UE5

### ISSUE THREAD

**Issue by westshawn** [DaedalicEntertainment/ue4-test-automation#25]
In UE5 Preview 1, Gauntlet targets "netcoreapp3.1" and DaedalicTestAutomation targets .NetFramework4.6.2, which makes the sln fail to compile.

Are there plans to add support for UE5?

**Comment by janousch** [comment]
It looks like they fixed the problem in Preview 2.
![image](https://user-images.githubusercontent.com/19645933/159159208-9a9327fa-40d5-4a45-8251-2818dc96a207.png)

**Comment by janousch** [comment]
Added UE5 support in commit 2eb9fe8d3675162189615771d1144fc775e2c326.
